### ISSUE TITLE
Klicking at tags results in 404

### ISSUE THREAD

**Issue by mgh87** [alexander-heimbuch/vuepress-theme-casper#3]
Hey, I just clicked around a little in your demo and noticed that opening tags results in a 404.
http://alexander.heimbu.ch/vuepress-theme-casper/tags/kill%20me/
Do you need to create extra markdown files for the tags or is something wrong with the creation?

I'm not that fit in the theme creation area yet so I didn't come up with a solution to solve this *g*.

**Comment by mgh87** [comment]
Ah ok. That's good to here, so in the vuepress build step something gets lost on the way?

**Comment by alexander-heimbuch** [comment]
I traced the bug down to the Header Component Slot, still not sure why the slot is causing the error :/

**Comment by alexander-heimbuch** [comment]
fixed in Version 1.1.1
