### ISSUE TITLE
After deploying with Stackbit and NetlifyCMS I cant login

### ISSUE THREAD

**Issue by rrhernandez** [alexander-heimbuch/vuepress-theme-casper#7]
After deploying with Stackbit and NetlifyCMS I cant login in Netlify CMS. I get the invite mail and when I click to accept the web page open but the netlify cms login appears BEHIND the content and I can't click in the form to complete the sigunp.

**Comment by alexander-heimbuch** [comment]
This repository only provides a configuration for netlify and isn't associated with it. Please contact @benedfit if you have any issues with this integration.

**Comment by benedfit** [comment]
I've got a member of our team looking into it

**Comment by JugglerX** [comment]
Here is a screenshot of the issue. It's simply that the login model for Netlify CMS has a lower z-index then some of the other absolute elements in the theme, so it appears behind the first blog post image.

![Screen Shot 2019-08-22 at 10 41 03 am](https://user-images.githubusercontent.com/1386506/63477800-4c0eff80-c4ca-11e9-86d9-153536dd06af.png)

I will PR a fix
